### ISSUE TITLE
'coverage' error

### ISSUE THREAD

**Issue by AnnadeShort** [amine0110/Medical-Conversions#2] opened 2022-06-20 14:43 UTC
Dear Amine,

Thank you so much for your script. It's great.

I encountered a problem during installing of the GUI. When I run this line: pip install -r requirements.txt
It says: "Couldn't find index page for "coverage" (maybe misspelled?)
No local packages or working download links found for coverage. See below for the full error message.
Could you maybe help me with this?

Thanks a lot in advance,

Kind regards,

Anna 

pip install -r requirements.txt
Collecting dicom2nifti==2.3.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/26/f1/22e4cb6704a5204b9ed731e74fac180b3659c0a1af65f6e2b149013bda21/dicom2nifti-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'coverage' (maybe misspelled?)
    No local packages or working download links found for coverage
    Starting pypi release version 2.3.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aNKbJO/dicom2nifti/setup.py", line 41, in <module>
        setup_requires=['nose', 'coverage']
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/mrphys/anndkor/.conda/envs/demo/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('coverage')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aNKbJO/dicom2nifti/
You are using pip version 9.0.1, however version 22.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by amine0110** [comment] 2022-06-20 14:51
Hi Anna,

Please try installing the packages directly with `pip install package` without specifying the version. Please let me know if you have any other issues.

Bests

**Comment by AnnadeShort** [comment] 2022-06-20 15:02
Thank you very much for your extremely quick reply!!!!

I did what you said.

However, I still get an error message when I try to run the main script (main.py)

$ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tkinter import *
ImportError: No module named tkinter


Do you have any idea what Im doing wrong?

Kind regards,

Anna

**Comment by amine0110** [comment] 2022-06-20 16:06
Try using `from Tkinter import *` with an upper T (in some python versions it needs to be included like that)

**Comment by AnnadeShort** [comment] 2022-06-20 16:14
Thank you!!! I am one step further. However now it seems that “filedialog”  is not recognized anymore. Any idea how that is caused?

***@***.***




Van: Mokhtari Mohammed El Amine ***@***.***>
Verzonden: maandag 20 juni 2022 18:07
Aan: amine0110/Medical-Conversions ***@***.***>
CC: Kort, Anna de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [amine0110/Medical-Conversions] 'coverage' error (Issue #2)


Try using Tkinter with an upper T (in some python versions it needs to be included like that)

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famine0110%2FMedical-Conversions%2Fissues%2F2%23issuecomment-1160624192&data=05%7C01%7Canna.dekort%40radboudumc.nl%7Cd7e166cb56374634e01f08da52d6de58%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637913380042539878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NzJI8Vhzrr64xWKjWIpbiJq2FoofBd%2FV282%2FhUcycow%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZW7JA3RGQ2JRMW5OBETK6TVQCJJFANCNFSM5ZJFTHCA&data=05%7C01%7Canna.dekort%40radboudumc.nl%7Cd7e166cb56374634e01f08da52d6de58%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637913380042539878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jNHZJJdC7S9To%2BwQfyc8gkxEMvVUy2yemyjSYNe9BJI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

De informatie in dit bericht is uitsluitend bestemd voor de geadresseerde. Aan dit bericht en de bijlagen kunnen geen rechten worden ontleend. Heeft u deze e-mail onbedoeld ontvangen? Dan verzoeken wij u het te vernietigen en de afzender te informeren. Openbaar maken, kopiëren en verspreiden van deze e-mail of informatie uit deze e-mail is alleen toegestaan met voorafgaande schriftelijke toestemming van de afzender. Het Radboudumc staat geregistreerd bij de Kamer van Koophandel in het handelsregister onder nummer 80262783.

The content of this message is intended solely for the addressee. No rights can be derived from this message or its attachments. If you are not the intended recipient, we kindly request you to delete the message and inform the sender. It is strictly prohibited to disclose, copy or distribute this email or the information inside it, without a written consent from the sender. Radboud university medical center is registered with the Dutch Chamber of Commerce trade register with number 80262783.

**Comment by amine0110** [comment] 2022-06-20 16:16
Which Python version are you using?

**Comment by AnnadeShort** [comment] 2022-06-20 16:23
I use conda version 4.3.8 and python 2.7.13



Van: Mokhtari Mohammed El Amine ***@***.***>
Verzonden: maandag 20 juni 2022 18:16
Aan: amine0110/Medical-Conversions ***@***.***>
CC: Kort, Anna de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [amine0110/Medical-Conversions] 'coverage' error (Issue #2)


Which Python version are you using?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famine0110%2FMedical-Conversions%2Fissues%2F2%23issuecomment-1160633963&data=05%7C01%7Canna.dekort%40radboudumc.nl%7Cd399d6cfc5924993f8d808da52d83451%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637913385781253432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P5p5cSgPEVjgxo0MtLle5G%2FIzmzX%2FGDBq%2BVb6W4inOE%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZW7JA4DFIQ2N354RT5U7LTVQCKM3ANCNFSM5ZJFTHCA&data=05%7C01%7Canna.dekort%40radboudumc.nl%7Cd399d6cfc5924993f8d808da52d83451%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637913385781263424%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B%2FsPdFXEAvGB9l9VNmxpljFte1TnX4635diOpZHyAIk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

De informatie in dit bericht is uitsluitend bestemd voor de geadresseerde. Aan dit bericht en de bijlagen kunnen geen rechten worden ontleend. Heeft u deze e-mail onbedoeld ontvangen? Dan verzoeken wij u het te vernietigen en de afzender te informeren. Openbaar maken, kopiëren en verspreiden van deze e-mail of informatie uit deze e-mail is alleen toegestaan met voorafgaande schriftelijke toestemming van de afzender. Het Radboudumc staat geregistreerd bij de Kamer van Koophandel in het handelsregister onder nummer 80262783.

The content of this message is intended solely for the addressee. No rights can be derived from this message or its attachments. If you are not the intended recipient, we kindly request you to delete the message and inform the sender. It is strictly prohibited to disclose, copy or distribute this email or the information inside it, without a written consent from the sender. Radboud university medical center is registered with the Dutch Chamber of Commerce trade register with number 80262783.

**Comment by amine0110** [comment] 2022-06-20 21:31
Please try to use 3.7 or up.

**Comment by amine0110** [comment] 2022-06-21 20:23
I am closing this issue, please reopen it if you are still having problems.
Bests

**Closed as completed by amine0110** 2022-06-21 20:23 UTC

**Comment by AnnadeShort** [comment] 2022-07-07 08:38
Dear Mokthari,

I have one more small question. Does your program also work with .nii.gz files?

Thank you in advance!

Kind regards,

Anna

Van: Mokhtari Mohammed El Amine ***@***.***>
Verzonden: dinsdag 21 juni 2022 22:24
Aan: amine0110/Medical-Conversions ***@***.***>
CC: Kort, Anna de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [amine0110/Medical-Conversions] 'coverage' error (Issue #2)


Closed #2<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famine0110%2FMedical-Conversions%2Fissues%2F2&data=05%7C01%7Canna.dekort%40radboudumc.nl%7C07d30142a65d49ebb5a708da53c3ef6f%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637914398241298092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zZAHsnZf8MXckXqxTaIl5JywAOSXQm4aknt3BTPJOBM%3D&reserved=0> as completed.

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famine0110%2FMedical-Conversions%2Fissues%2F2%23event-6850769242&data=05%7C01%7Canna.dekort%40radboudumc.nl%7C07d30142a65d49ebb5a708da53c3ef6f%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637914398241298092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XwBajgvG%2FF%2FsdR3mCF0srs9anZEmsb6asbyBHVy1iCE%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZW7JA6XMLVSIJFZMM54B2DVQIQE3ANCNFSM5ZJFTHCA&data=05%7C01%7Canna.dekort%40radboudumc.nl%7C07d30142a65d49ebb5a708da53c3ef6f%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637914398241298092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jk4ofZsJsAd%2F%2FV70So5C5M3LtFe35Ge4lnikLL8VKDI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

De informatie in dit bericht is uitsluitend bestemd voor de geadresseerde. Aan dit bericht en de bijlagen kunnen geen rechten worden ontleend. Heeft u deze e-mail onbedoeld ontvangen? Dan verzoeken wij u het te vernietigen en de afzender te informeren. Openbaar maken, kopiëren en verspreiden van deze e-mail of informatie uit deze e-mail is alleen toegestaan met voorafgaande schriftelijke toestemming van de afzender. Het Radboudumc staat geregistreerd bij de Kamer van Koophandel in het handelsregister onder nummer 80262783.

The content of this message is intended solely for the addressee. No rights can be derived from this message or its attachments. If you are not the intended recipient, we kindly request you to delete the message and inform the sender. It is strictly prohibited to disclose, copy or distribute this email or the information inside it, without a written consent from the sender. Radboud university medical center is registered with the Dutch Chamber of Commerce trade register with number 80262783.

**Comment by amine0110** [comment] 2022-07-07 08:45
Hi Anna
Yes it does support.

Bests

**Comment by AnnadeShort** [comment] 2022-07-07 09:36
Okay! Thank you.

I keep getting below error messages when I try to convert nifti to dicom.
Do you have any idea what I am doing wrong?

Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/anaconda3/2021.05/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 308, in call_convert_save_nifti_to_dicom
    convert_nifti_to_dicom(image, o_path)
  File "/project/3015077.01/res/Medical-Conversions/functions.py", line 93, in convert_nifti_to_dicom
    list(map(lambda i: writeSlices(series_tag_values, new_img, i, out_dir), range(new_img.GetDepth())))
  File "/project/3015077.01/res/Medical-Conversions/functions.py", line 93, in <lambda>
    list(map(lambda i: writeSlices(series_tag_values, new_img, i, out_dir), range(new_img.GetDepth())))
  File "/project/3015077.01/res/Medical-Conversions/functions.py", line 75, in writeSlices
    writer.Execute(image_slice)
  File "/home/mrphys/anndkor/.local/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 7503, in Execute
    return _SimpleITK.ImageFileWriter_Execute(self, *args)
RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1212:
ITK ERROR: GDCMImageIO(0x5628662834c0): A Floating point buffer was passed but the stored pixel type was not specified.This is currently not supported

Van: Mokhtari Mohammed El Amine ***@***.***>
Verzonden: donderdag 7 juli 2022 10:46
Aan: amine0110/Medical-Conversions ***@***.***>
CC: Kort, Anna de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [amine0110/Medical-Conversions] 'coverage' error (Issue #2)


Hi Anna
Yes it does support.

Bests

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famine0110%2FMedical-Conversions%2Fissues%2F2%23issuecomment-1177264677&data=05%7C01%7Canna.dekort%40radboudumc.nl%7C0ff085a9e95c4ae4ebee08da5ff51b09%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637927803562993318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sG%2BfYnG7GaHezAM%2F0imp4nO0JDb6IB61Q1fdYgO6lCM%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZW7JAYD2SUIOQMMWOIUB3DVS2KMDANCNFSM5ZJFTHCA&data=05%7C01%7Canna.dekort%40radboudumc.nl%7C0ff085a9e95c4ae4ebee08da5ff51b09%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637927803563149539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aA33yJ4Mvpc%2BHmCZHAHF60SV2LAuMV6ABBt1AvcWOVY%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

De informatie in dit bericht is uitsluitend bestemd voor de geadresseerde. Aan dit bericht en de bijlagen kunnen geen rechten worden ontleend. Heeft u deze e-mail onbedoeld ontvangen? Dan verzoeken wij u het te vernietigen en de afzender te informeren. Openbaar maken, kopiëren en verspreiden van deze e-mail of informatie uit deze e-mail is alleen toegestaan met voorafgaande schriftelijke toestemming van de afzender. Het Radboudumc staat geregistreerd bij de Kamer van Koophandel in het handelsregister onder nummer 80262783.

The content of this message is intended solely for the addressee. No rights can be derived from this message or its attachments. If you are not the intended recipient, we kindly request you to delete the message and inform the sender. It is strictly prohibited to disclose, copy or distribute this email or the information inside it, without a written consent from the sender. Radboud university medical center is registered with the Dutch Chamber of Commerce trade register with number 80262783.

**Comment by amine0110** [comment] 2022-07-07 09:40
Can you please send me the file you are trying to convert so that I can test it to know if the problem is with the file or with the code.

pycad2020@gmail.com

**Comment by AnnadeShort** [comment] 2022-07-07 10:25
Thanks so much for your offer!!
I will ask the patient first if she is fine with it.

Van: Mokhtari Mohammed El Amine ***@***.***>
Verzonden: donderdag 7 juli 2022 11:40
Aan: amine0110/Medical-Conversions ***@***.***>
CC: Kort, Anna de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [amine0110/Medical-Conversions] 'coverage' error (Issue #2)


Can you please send me the file you are trying to convert so that I can test it to know if the problem is with the file or with the code.

***@***.******@***.***>

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famine0110%2FMedical-Conversions%2Fissues%2F2%23issuecomment-1177320888&data=05%7C01%7Canna.dekort%40radboudumc.nl%7Cbfb074b24d52482d00e108da5ffcb24d%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637927836162827039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5T8vbAD0lK9TF0eUUpTxbawS0aErNPzG7K2reG%2BX%2FSQ%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZW7JAYEP4KHD6HGUZ37T5LVS2QX5ANCNFSM5ZJFTHCA&data=05%7C01%7Canna.dekort%40radboudumc.nl%7Cbfb074b24d52482d00e108da5ffcb24d%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637927836162983249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r%2Br9StENZYRIME8869OsCEHBqZhMB6lI%2BWUo8KhCDcM%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

De informatie in dit bericht is uitsluitend bestemd voor de geadresseerde. Aan dit bericht en de bijlagen kunnen geen rechten worden ontleend. Heeft u deze e-mail onbedoeld ontvangen? Dan verzoeken wij u het te vernietigen en de afzender te informeren. Openbaar maken, kopiëren en verspreiden van deze e-mail of informatie uit deze e-mail is alleen toegestaan met voorafgaande schriftelijke toestemming van de afzender. Het Radboudumc staat geregistreerd bij de Kamer van Koophandel in het handelsregister onder nummer 80262783.

The content of this message is intended solely for the addressee. No rights can be derived from this message or its attachments. If you are not the intended recipient, we kindly request you to delete the message and inform the sender. It is strictly prohibited to disclose, copy or distribute this email or the information inside it, without a written consent from the sender. Radboud university medical center is registered with the Dutch Chamber of Commerce trade register with number 80262783.
